// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD34C3pBRuxmiFXstrnT96XG7MBBMvj1RY',
    appId: '1:320225809643:web:a31d24b122eadeecc4daae',
    messagingSenderId: '320225809643',
    projectId: 'chataeron-2ff0f',
    authDomain: 'chataeron-2ff0f.firebaseapp.com',
    storageBucket: 'chataeron-2ff0f.firebasestorage.app',
    measurementId: 'G-6HNY10ZMKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8BHu_8kX_BFlcidOE-aLQIjKJw2gyehs',
    appId: '1:320225809643:android:b336b43c6ca0121ac4daae',
    messagingSenderId: '320225809643',
    projectId: 'chataeron-2ff0f',
    storageBucket: 'chataeron-2ff0f.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA556acmt2V1BhmyeJMJU3GcRfT6cFnBQY',
    appId: '1:320225809643:ios:12b8a1ab3b19dfadc4daae',
    messagingSenderId: '320225809643',
    projectId: 'chataeron-2ff0f',
    storageBucket: 'chataeron-2ff0f.firebasestorage.app',
    iosBundleId: 'com.example.chatAeron',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA556acmt2V1BhmyeJMJU3GcRfT6cFnBQY',
    appId: '1:320225809643:ios:12b8a1ab3b19dfadc4daae',
    messagingSenderId: '320225809643',
    projectId: 'chataeron-2ff0f',
    storageBucket: 'chataeron-2ff0f.firebasestorage.app',
    iosBundleId: 'com.example.chatAeron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD34C3pBRuxmiFXstrnT96XG7MBBMvj1RY',
    appId: '1:320225809643:web:3b1ab03b7a671badc4daae',
    messagingSenderId: '320225809643',
    projectId: 'chataeron-2ff0f',
    authDomain: 'chataeron-2ff0f.firebaseapp.com',
    storageBucket: 'chataeron-2ff0f.firebasestorage.app',
    measurementId: 'G-0Q4FX3W7J9',
  );
}
